name: Deploy Flutter Web

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.1'  # Updated to match required version
          cache: true  # Add caching

      - name: Install Chrome (required for web build)
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev chromium-browser

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release
        env:
          FLUTTER_WEB: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web  # Flutter's web build directory
